# Generated by Django 5.1.2 on 2024-10-13 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('session_type', models.CharField(max_length=200)),
                ('ethnicity', models.CharField(max_length=200)),
                ('ethnicity_preference', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=100)),
                ('gender_preference', models.CharField(max_length=100)),
                ('mentoring_methods', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('mentor', 'Mentor'), ('mentee', 'Mentee')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('session_type', models.CharField(max_length=200)),
                ('ethnicity', models.CharField(max_length=200)),
                ('ethnicity_preference', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=100)),
                ('gender_preference', models.CharField(max_length=100)),
                ('mentoring_methods', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('mentor', 'Mentor'), ('mentee', 'Mentee')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_details', models.TextField()),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.mentee')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.mentor')),
            ],
        ),
    ]
