# Generated by Django 5.1.2 on 2024-10-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='ethnicity_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mentee',
            name='ethnicity_preference_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mentee',
            name='gender_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mentee',
            name='gender_preference_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mentee',
            name='mentoring_methods_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mentee',
            name='session_type_others',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='ethnicity_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='ethnicity_preference_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='gender_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='gender_preference_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='mentoring_methods_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='session_type_others',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='age',
            field=models.IntegerField(choices=[('9-13', '9-13'), ('13-18', '13-18'), ('18-22', '18-22'), ('22-30', '22-30'), ('30-40', '30-40'), ('40-50', '40-50'), ('50-60', '50-60'), ('60+', '60+')]),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='ethnicity',
            field=models.CharField(choices=[('American Indian or Alaska Native', 'American Indian or Alaska Native'), ('Asian', 'Asian: Includes Chinese, Japanese, Filipino, Korean, South Asian, and Vietnamese'), ('South Asian', 'South Asian: Includes Indian, Pakistan, Sri Lankan, Bangladesh'), ('Black or African American', 'Black or African American: Includes Jamaican, Nigerian, Haitian, and Ethiopian'), ('Hispanic or Latino', 'Hispanic or Latino: Includes Puerto Rican, Mexican, Cuban, Salvadoran, and Colombian'), ('Middle Eastern or North African', 'Middle Eastern or North African: Includes Lebanese, Iranian, Egyptian, Moroccan, Israeli, and Palestinian'), ('Native Hawaiian or Pacific Islander', 'Native Hawaiian or Pacific Islander: Includes Samoan, Guamanian, Chamorro, and Tongan'), ('White or European', 'White or European: Includes German, Irish, English, Italian, Polish, and French'), ('Other', 'Other')], max_length=200),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='ethnicity_preference',
            field=models.CharField(choices=[('Prefer ONLY to be matched within that similarity', 'Prefer ONLY to be matched within that similarity'), ('Prefer it, but available to others as needed', 'Prefer it, but available to others as needed'), ('Prefer NOT to be matched within that similarity', 'Prefer NOT to be matched within that similarity'), ('Do not have a preference. Either is fine.', 'Do not have a preference. Either is fine.'), ('Other', 'Other')], max_length=200),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='gender',
            field=models.CharField(choices=[('Cisgender Male', 'Cisgender Male'), ('Cisgender Female', 'Cisgender Female'), ('Transgender Male', 'Transgender Male'), ('Transgender Female', 'Transgender Female'), ('Prefer not to disclose', 'Prefer not to disclose'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='gender_preference',
            field=models.CharField(choices=[('Prefer ONLY to be matched within that similarity', 'Prefer ONLY to be matched within that similarity'), ('Prefer it, but available to others as needed', 'Prefer it, but available to others as needed'), ('Prefer NOT to be matched within that similarity', 'Prefer NOT to be matched within that similarity'), ('Do not have a preference. Either is fine.', 'Do not have a preference. Either is fine.'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='mentoring_methods',
            field=models.CharField(choices=[('Web conference', 'Web conference'), ('In person', 'In person'), ('Hybrid', 'Hybrid (both web and in person)'), ('Other', 'Other')], max_length=200),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='role',
            field=models.CharField(choices=[('Mentor', 'Mentor'), ('Mentee', 'Mentee')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='session_type',
            field=models.CharField(choices=[('Homework Help', 'Homework Help'), ('Exposure to STEAM', 'Exposure to STEAM'), ('College guidance', 'College guidance'), ('Career guidance', 'Career guidance'), ('Explore a particular field', 'Explore a particular field'), ('Other', 'Other')], max_length=200),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='state',
            field=models.CharField(choices=[('AL', 'AL: Alabama'), ('AK', 'AK: Alaska'), ('AZ', 'AZ: Arizona'), ('AR', 'AR: Arkansas'), ('CA', 'CA: California'), ('CO', 'CO: Colorado'), ('CT', 'CT: Connecticut'), ('DC', 'DC: District of Columbia'), ('DE', 'DE: Delaware'), ('FL', 'FL: Florida'), ('GA', 'GA: Georgia'), ('HI', 'HI: Hawaii'), ('ID', 'ID: Idaho'), ('IL', 'IL: Illinois'), ('IN', 'IN: Indiana'), ('IA', 'IA: Iowa'), ('KS', 'KS: Kansas'), ('KY', 'KY: Kentucky'), ('LA', 'LA: Louisiana'), ('ME', 'ME: Maine'), ('MD', 'MD: Maryland'), ('MA', 'MA: Massachussetts'), ('MI', 'MI: Michigan'), ('MN', 'MN: Minnesota'), ('MS', 'MS: Mississippi'), ('MO', 'MO: Missouri'), ('MT', 'MT: Montana'), ('NE', 'NE: Nebraska'), ('NV', 'NV: Nevada'), ('NH', 'NH: New Hampshire'), ('NJ', 'NJ: New Jersey'), ('NM', 'NM: New Mexico'), ('NY', 'NY: New York'), ('NC', 'NC: North Carolina'), ('ND', 'ND: North Dakota'), ('OH', 'OH: Ohio'), ('OK', 'OK: Oklahoma'), ('OR', 'OR: Oregon'), ('PA', 'PA: Pennsylvania'), ('RI', 'RI: Rhode Island'), ('SC', 'SC: South Carolina'), ('SD', 'SD: South Dakota'), ('TN', 'TN: Tennessee'), ('TX', 'TX: Texas'), ('UT', 'UT: Utah'), ('VT', 'VT: Vermont'), ('VA', 'VA: Virginia'), ('WA', 'WA: Washington'), ('WV', 'WV: West Virginia'), ('WI', 'WI: Wisconsin'), ('WY', 'WY: Wyoming')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='age',
            field=models.IntegerField(choices=[('9-13', '9-13'), ('13-18', '13-18'), ('18-22', '18-22'), ('22-30', '22-30'), ('30-40', '30-40'), ('40-50', '40-50'), ('50-60', '50-60'), ('60+', '60+')]),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='ethnicity',
            field=models.CharField(choices=[('American Indian or Alaska Native', 'American Indian or Alaska Native'), ('Asian', 'Asian: Includes Chinese, Japanese, Filipino, Korean, South Asian, and Vietnamese'), ('South Asian', 'South Asian: Includes Indian, Pakistan, Sri Lankan, Bangladesh'), ('Black or African American', 'Black or African American: Includes Jamaican, Nigerian, Haitian, and Ethiopian'), ('Hispanic or Latino', 'Hispanic or Latino: Includes Puerto Rican, Mexican, Cuban, Salvadoran, and Colombian'), ('Middle Eastern or North African', 'Middle Eastern or North African: Includes Lebanese, Iranian, Egyptian, Moroccan, Israeli, and Palestinian'), ('Native Hawaiian or Pacific Islander', 'Native Hawaiian or Pacific Islander: Includes Samoan, Guamanian, Chamorro, and Tongan'), ('White or European', 'White or European: Includes German, Irish, English, Italian, Polish, and French'), ('Other', 'Other')], max_length=200),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='ethnicity_preference',
            field=models.CharField(choices=[('Prefer ONLY to be matched within that similarity', 'Prefer ONLY to be matched within that similarity'), ('Prefer it, but available to others as needed', 'Prefer it, but available to others as needed'), ('Prefer NOT to be matched within that similarity', 'Prefer NOT to be matched within that similarity'), ('Do not have a preference. Either is fine.', 'Do not have a preference. Either is fine.'), ('Other', 'Other')], max_length=200),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='gender',
            field=models.CharField(choices=[('Cisgender Male', 'Cisgender Male'), ('Cisgender Female', 'Cisgender Female'), ('Transgender Male', 'Transgender Male'), ('Transgender Female', 'Transgender Female'), ('Prefer not to disclose', 'Prefer not to disclose'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='gender_preference',
            field=models.CharField(choices=[('Prefer ONLY to be matched within that similarity', 'Prefer ONLY to be matched within that similarity'), ('Prefer it, but available to others as needed', 'Prefer it, but available to others as needed'), ('Prefer NOT to be matched within that similarity', 'Prefer NOT to be matched within that similarity'), ('Do not have a preference. Either is fine.', 'Do not have a preference. Either is fine.'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='mentoring_methods',
            field=models.CharField(choices=[('Web conference', 'Web conference'), ('In person', 'In person'), ('Hybrid', 'Hybrid (both web and in person)'), ('Other', 'Other')], max_length=200),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='role',
            field=models.CharField(choices=[('Mentor', 'Mentor'), ('Mentee', 'Mentee')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='session_type',
            field=models.CharField(choices=[('Homework Help', 'Homework Help'), ('Exposure to STEAM', 'Exposure to STEAM'), ('College guidance', 'College guidance'), ('Career guidance', 'Career guidance'), ('Explore a particular field', 'Explore a particular field'), ('Other', 'Other')], max_length=200),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='state',
            field=models.CharField(choices=[('AL', 'AL: Alabama'), ('AK', 'AK: Alaska'), ('AZ', 'AZ: Arizona'), ('AR', 'AR: Arkansas'), ('CA', 'CA: California'), ('CO', 'CO: Colorado'), ('CT', 'CT: Connecticut'), ('DC', 'DC: District of Columbia'), ('DE', 'DE: Delaware'), ('FL', 'FL: Florida'), ('GA', 'GA: Georgia'), ('HI', 'HI: Hawaii'), ('ID', 'ID: Idaho'), ('IL', 'IL: Illinois'), ('IN', 'IN: Indiana'), ('IA', 'IA: Iowa'), ('KS', 'KS: Kansas'), ('KY', 'KY: Kentucky'), ('LA', 'LA: Louisiana'), ('ME', 'ME: Maine'), ('MD', 'MD: Maryland'), ('MA', 'MA: Massachussetts'), ('MI', 'MI: Michigan'), ('MN', 'MN: Minnesota'), ('MS', 'MS: Mississippi'), ('MO', 'MO: Missouri'), ('MT', 'MT: Montana'), ('NE', 'NE: Nebraska'), ('NV', 'NV: Nevada'), ('NH', 'NH: New Hampshire'), ('NJ', 'NJ: New Jersey'), ('NM', 'NM: New Mexico'), ('NY', 'NY: New York'), ('NC', 'NC: North Carolina'), ('ND', 'ND: North Dakota'), ('OH', 'OH: Ohio'), ('OK', 'OK: Oklahoma'), ('OR', 'OR: Oregon'), ('PA', 'PA: Pennsylvania'), ('RI', 'RI: Rhode Island'), ('SC', 'SC: South Carolina'), ('SD', 'SD: South Dakota'), ('TN', 'TN: Tennessee'), ('TX', 'TX: Texas'), ('UT', 'UT: Utah'), ('VT', 'VT: Vermont'), ('VA', 'VA: Virginia'), ('WA', 'WA: Washington'), ('WV', 'WV: West Virginia'), ('WI', 'WI: Wisconsin'), ('WY', 'WY: Wyoming')], max_length=50),
        ),
    ]
